### ISSUE TITLE
Keysound not found 

### ISSUE THREAD

**Issue by bobbypfreely** [MineEric64/UniConverter-Project#5]
When loading in sounds everything seems to load except it throws a error message, "keysound file not exists"

**Comment by MineEric64** [comment]
can you show me error message as an image?

**Comment by bobbypfreely** [comment]
That was actually not in the latest beta. I downloaded the stable version
but yes I'll upload a pic with this. I do gotta say instead of another
issue, on the latest beta not needing permission to use, I believe it's 7
or 8 the pack is converted wonderfully, only unipad doesn't recognize info
or key sound files. I talk to you a lot on discord, I'll hit you up there
you can close this issue tho buddy

**Comment by MineEric64** [comment]
alright, when you need to reopen the issue, you can reopen it and tell me about that anytime.
